CREATE OR REPLACE FUNCTION F_GET_SUBMISSIONS (C_ID NUMBER)
RETURN V
AS
  V_SUBMISSIONS V;
BEGIN
SELECT PAPER_ID, TITLE, ABSTRACT, TEXT, 'UNKNOWN_AUTH' BULK COLLECT INTO V_SUBMISSIONS
FROM PAPERS
WHERE PAPER_ID IN (SELECT PAPER_ID
                   FROM SUBMISSIONS
                   WHERE CONFERENCE_ID = C_ID);
RETURN V_SUBMISSIONS;
END;
