CREATE TYPE PAPER_TYPE AS OBJECT(ID NUMBER , TITLE VARCHAR2(100), TEXT VARCHAR2(2));
CREATE TYPE PROGRAM_ARR_TYPE AS VARRAY(1000) OF PAPER_TYPE;
CREATE OR REPLACE FUNCTION F_GET_SECTION_PROGRAM (S_ID NUMBER)
RETURN PROGRAM_ARR_TYPE
AS
  V_PROGRAM PROGRAM_ARR_TYPE;
BEGIN
SELECT PAPER_ID, TITLE, ABSTRACT, TEXT, 'UNKNOWN_AUTH' BULK COLLECT
INTO V_PROGRAM
FROM PAPERS
WHERE PAPER_ID IN (SELECT PAPER_ID
                   FROM ALLOCATIONS
                   WHERE SESSION_ID = S_ID);
RETURN V_PROGRAM;
END;
