------------------------------- MODULE Main -------------------------------
EXTENDS RuntimeFS
f_UCHEBA_programm_list_load(id) ==
IF XLocks = Undef
THEN
/\ XLocks' = id
/\ Sessions' =
 [
 Sessions EXCEPT ![id]["SessionM"] = Sessions[id]["SessionM"] \o
 <<min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 f_UCHEBA_programm_list_v_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c11(id).policy,
 f_UCHEBA_programm_list_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_r_rec_c11(id).policy>>
 ]
/\ New2Old' =
 <<
 <<f_UCHEBA_programm_list_p_data_view(id).policy,
 f_UCHEBA_programm_list_p_data_unuse(id).policy,
 f_UCHEBA_programm_list_p_data_name(id).policy,
 f_UCHEBA_programm_list_p_data_code(id).policy,
 f_UCHEBA_programm_list_p_date_n(id).policy,
 f_UCHEBA_programm_list_p_date_o(id).policy,
 f_UCHEBA_programm_list_p_data_naprav(id).policy,
 f_UCHEBA_programm_list_p_data_kafedra(id).policy,
 f_UCHEBA_programm_list_p_data_chacov_n(id).policy,
 f_UCHEBA_programm_list_p_data_chacov_o(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c11(id).policy,
 f_UCHEBA_programm_list_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_r_rec_c11(id).policy>>,
 <<min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 min,
 f_UCHEBA_programm_list_v_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_v_r_rec_c11(id).policy,
 f_UCHEBA_programm_list_r_rec_c1(id).policy,
 f_UCHEBA_programm_list_r_rec_c2(id).policy,
 f_UCHEBA_programm_list_r_rec_c3(id).policy,
 f_UCHEBA_programm_list_r_rec_c4(id).policy,
 f_UCHEBA_programm_list_r_rec_c5(id).policy,
 f_UCHEBA_programm_list_r_rec_c6(id).policy,
 f_UCHEBA_programm_list_r_rec_c7(id).policy,
 f_UCHEBA_programm_list_r_rec_c8(id).policy,
 f_UCHEBA_programm_list_r_rec_c9(id).policy,
 f_UCHEBA_programm_list_r_rec_c10(id).policy,
 f_UCHEBA_programm_list_r_rec_c11(id).policy>>
 >>
/\ Ignore' = 0
/\ SLocks' = SLocks
/\ StateE' = SLocks'[id]
/\ UNCHANGED <<VPol>>
ELSE UNCHANGED vars

f_UCHEBA_programm_list31(id) ==
/\ select(id, <<
 f_UCHEBA_programm_list_v_r_rec_c1(id),
 f_UCHEBA_programm_list_v_r_rec_c2(id),
 f_UCHEBA_programm_list_v_r_rec_c3(id),
 f_UCHEBA_programm_list_v_r_rec_c4(id),
 f_UCHEBA_programm_list_v_r_rec_c5(id),
 f_UCHEBA_programm_list_v_r_rec_c6(id),
 f_UCHEBA_programm_list_v_r_rec_c7(id),
 f_UCHEBA_programm_list_v_r_rec_c8(id),
 f_UCHEBA_programm_list_v_r_rec_c9(id),
 f_UCHEBA_programm_list_v_r_rec_c10(id),
 f_UCHEBA_programm_list_v_r_rec_c11(id)>>,
 <<
 VPol["col_uch_programm_programm_id"].policy,
 VPol["col_uch_programm_name"].policy,
 VPol["col_uch_programm_short_name"].policy,
 VPol["col_uch_programm_count_chasov"].policy,
 VPol["col_uch_programm_count_chasov_audit"].policy,
 VPol["col_uch_programm_data"].policy,
 VPol["col_uch_programm_fullnumber"].policy,
 VPol["col_uch_programm_code"].policy,
 VPol["col_uch_napravlenie_short_name"].policy,
 VPol["col_uch_napravlenie_name"].policy,
 VPol["col_upr_department_short_title"].policy>>,
 LUB4Seq(<<
 load(id, f_UCHEBA_programm_list_p_data_view(id)),
 load(id, f_UCHEBA_programm_list_p_date_n(id)),
 load(id, f_UCHEBA_programm_list_p_date_o(id)),
 load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 VPol["col_uch_programm_napr_id"].policy,
 VPol["col_uch_napravlenie_id"].policy,
 VPol["col_uch_programm_department_id"].policy,
 VPol["col_upr_department_id"].policy,
 VPol["col_uch_programm_type"].policy,
 VPol["col_uch_programm_id"].policy,
 VPol["col_uch_programm_name"].policy,
 VPol["col_uch_programm_code"].policy,
 VPol["col_uch_programm_data"].policy,
 VPol["col_uch_programm_napravlenie"].policy,
 VPol["col_uch_programm_department"].policy,
 VPol["col_uch_programm_count_chasov"].policy,
 VPol["col_uch_programm_unuse"].policy>>),
 <<
 "f_UCHEBA_programm_list", "lbl_33"
 >>)
/\ Trace' = Append(Trace,<<id,
 "f_UCHEBA_programm_list31",
 "SELECT uch_programm . programm_id , uch_programm . name , uch_programm . short_name , uch_programm . count_chasov , uch_programm . count_chasov_audit , uch_programm . data , uch_programm . fullnumber , uch_programm . code , uch_napravlenie . short_name , uch_napravlenie . name , upr_department . short_title INTO r FROM uch_programm WHERE uch_programm . napr_id = uch_napravlenie . id and uch_programm . department_id = upr_department . id and uch_programm . type = '89878DB1-1E71-4E6C-B615-9085F2ED964D' and uch_programm . id <> data_view and uch_programm . name LIKE '%' + data_name + '%' and uch_programm . code LIKE '%' + data_code + '%' and uch_programm . data > = date_n and uch_programm . data < = date_o and uch_programm . napravlenie = data_naprav and uch_programm . department = data_kafedra and uch_programm . count_chasov = data_chacov_n and uch_programm . count_chasov = data_chacov_o and uch_programm . unuse = data_unuse",
 [from |-> <<
 <<
 [policy |-> min, name |-> "literal_2"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_3"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_4"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_5"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_6"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_7"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_8"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_9"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_10"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_11"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>,
 <<
 [policy |-> min, name |-> "literal_12"],
 [policy |-> min, name |-> "literal_1"],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_view(id)),
 name |-> f_UCHEBA_programm_list_p_data_view(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_n(id)),
 name |-> f_UCHEBA_programm_list_p_date_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_date_o(id)),
 name |-> f_UCHEBA_programm_list_p_date_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_naprav(id)),
 name |-> f_UCHEBA_programm_list_p_data_naprav(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_kafedra(id)),
 name |-> f_UCHEBA_programm_list_p_data_kafedra(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_n(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_n(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_chacov_o(id)),
 name |-> f_UCHEBA_programm_list_p_data_chacov_o(id).name],
 [policy |-> load(id, f_UCHEBA_programm_list_p_data_unuse(id)),
 name |-> f_UCHEBA_programm_list_p_data_unuse(id).name],
 VPol.col_uch_programm_napr_id,
 VPol.col_uch_napravlenie_id,
 VPol.col_uch_programm_department_id,
 VPol.col_upr_department_id,
 VPol.col_uch_programm_type,
 VPol.col_uch_programm_id,
 VPol.col_uch_programm_name,
 VPol.col_uch_programm_code,
 VPol.col_uch_programm_data,
 VPol.col_uch_programm_napravlenie,
 VPol.col_uch_programm_department,
 VPol.col_uch_programm_count_chasov,
 VPol.col_uch_programm_unuse
 >>
 >>,
 to |-> <<
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c1(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c1(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c2(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c2(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c3(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c3(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c4(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c4(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c5(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c5(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c6(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c6(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c7(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c7(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c8(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c8(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c9(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c9(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c10(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c10(id).name],
 policy |-> load(id, f_UCHEBA_programm_list_v_r_rec_c11(id)),
 name |-> f_UCHEBA_programm_list_v_r_rec_c11(id).name]>>
 ]>>)
/\ Ignore' = 0
/\ SLocks' = SLocks
/\ StateE' = SLocks'[id]
/\ UNCHANGED <<XLocks, VPol>>

f_UCHEBA_programm_list33(id) ==
/\ return(id, <<
 f_UCHEBA_programm_list_r_rec_c1(id),
 f_UCHEBA_programm_list_r_rec_c2(id),
 f_UCHEBA_programm_list_r_rec_c3(id),
 f_UCHEBA_programm_list_r_rec_c4(id),
 f_UCHEBA_programm_list_r_rec_c5(id),
 f_UCHEBA_programm_list_r_rec_c6(id),
 f_UCHEBA_programm_list_r_rec_c7(id),
 f_UCHEBA_programm_list_r_rec_c8(id),
 f_UCHEBA_programm_list_r_rec_c9(id),
 f_UCHEBA_programm_list_r_rec_c10(id),
 f_UCHEBA_programm_list_r_rec_c11(id)>>,
 <<
 load(id, f_UCHEBA_programm_list_v_r_rec_c1(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c2(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c3(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c4(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c5(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c6(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c7(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c8(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c9(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c10(id)),
 load(id, f_UCHEBA_programm_list_v_r_rec_c11(id))>>,
 <<
 "f_UCHEBA_programm_list", "exit"
 >>)
/\ Trace' = Append(Trace,<<>>)
/\ Ignore' = 0
/\ SLocks' = SLocks
/\ StateE' = SLocks'[id]
/\ XLocks' = XLocks
/\ VPol' = VPol

f_UCHEBA_programm_list_exit(id) ==
/\ IF Len(Sessions[id]["StateRegs"]) = 1
 THEN XLocks' = Undef
 ELSE XLocks' = XLocks
/\ Sessions' =
 [Sessions EXCEPT
 ![id]["StateRegs"] = Tail(Sessions[id]["StateRegs"]) \o <<>>,
 ![id]["Ret"] =
 <<
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c1(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c2(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c3(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c4(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c5(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c6(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c7(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c8(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c9(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c10(id).offs],
 Sessions[id]["SessionM"][Head(Sessions[id]["StateRegs"]).fp + f_UCHEBA_programm_list_r_rec_c11(id).offs]
 >>,
 ![id]["SessionM"] = SubSeq(Sessions[id]["SessionM"], 1, Len(Sessions[id]["SessionM"]) - 32)]
/\ Trace' = Append(Trace, <<id,"f_UCHEBA_programm_list_exit",
 "f_UCHEBA_programm_list_exit",
 [from |-> << >>, to |-> << >>]>>)
 /\ Ignore' = 1
/\ SLocks' = SLocks
/\ StateE' = SLocks'[id]
/\ UNCHANGED <<New2Old, VPol>>

f_UCHEBA_programm_list(id,st) ==
 CASE Head(st).pc[2] = "lbl_31" -> f_UCHEBA_programm_list31(id)
[] Head(st).pc[2] = "lbl_33" -> f_UCHEBA_programm_list33(id)
[] Head(st).pc[2] = "exit" -> f_UCHEBA_programm_list_exit(id)
[] OTHER -> UNCHANGED vars

dispatch(id,st) ==
CASE
/\ Head(st).pc[1] = "f_UCHEBA_programm_list"
/\ Sessions[id]["SessionM"] = <<>> ->
   /\ f_UCHEBA_programm_list_load(id)
   /\ Trace' = Append(Trace,<<>>)
[] /\ Head(st).pc[1] = "f_UCHEBA_programm_list"
/\ Sessions[id]["SessionM"] # <<>> -> f_UCHEBA_programm_list(id, st)

Init ==
LET pc == [{"pc"} ->
{<<"f_UCHEBA_programm_list", "lbl_31">>}
]
IN
/\ Trace = <<>>
/\ StateE = [e1 \in E0 |-> {}] @@ [e2 \in E1 |-> {}]
/\ Sessions \in 
     [S -> 
          ReduceSet(LAMBDA x, y: x \cup 
              {y @@ [SessionM |-> <<>>]
                 @@ [PCLabel  |-> <<min>>]
                 @@ [Ret      |-> Undef]},
                 {}, 
                 [{"StateRegs"} -> 
                      ReduceSet (LAMBDA x, y: 
                          x \cup ({<<y @@ [fp |->1]>>}), {}, pc) ])
     ]
/\ SLocks = 
     [s \in S |-> [e1 \in E0 |-> {}] 
      @@ [e2 \in E1 |-> {}]]
/\ New2Old = <<>>
/\ Ignore = 0
/\ XLocks = Undef
/\ VPol =
 [
 col_uch_napravlenie_id |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_id"],
 col_uch_napravlenie_head_id |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_head_id"],
 col_uch_napravlenie_name |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_name"],
 col_uch_napravlenie_short_name |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_short_name"],
 col_uch_napravlenie_code |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_code"],
 col_uch_napravlenie_order |-> [ext|->0, policy |-> min, name |-> "col_uch_napravlenie_order"],

 col_uch_program_child_count |-> [ext|->0, policy |-> min, name |-> "col_uch_program_child_count"],
 col_uch_program_child_razdel |-> [ext|->0, policy |-> min, name |-> "col_uch_program_child_razdel"],
 col_uch_program_name |-> [ext|->0, policy |-> min, name |-> "col_uch_program_name"],
 col_uch_program_sname |-> [ext|->0, policy |-> min, name |-> "col_uch_program_sname"],
 col_uch_program_tname |-> [ext|->0, policy |-> min, name |-> "col_uch_program_tname"],
 col_uch_program_code |-> [ext|->0, policy |-> min, name |-> "col_uch_program_code"],
 col_uch_program_date |-> [ext|->0, policy |-> min, name |-> "col_uch_program_date"],
 col_uch_program_type |-> [ext|->0, policy |-> min, name |-> "col_uch_program_type"],
 col_uch_program_chasov |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov"],
 col_uch_program_chasov_aud |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_aud"],
 col_uch_program_chasov_l |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_l"],
 col_uch_program_chasov_p |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_p"],
 col_uch_program_chasov_s |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_s"],
 col_uch_program_chasov_o |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_o"],
 col_uch_program_chasov_o_name |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_o_name"],
 col_uch_program_chasov_sam_pr |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_sam_pr"],
 col_uch_program_chasov_sam |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_sam"],
 col_uch_program_chasov_att |-> [ext|->0, policy |-> min, name |-> "col_uch_program_chasov_att"],
 col_uch_program_category |-> [ext|->0, policy |-> min, name |-> "col_uch_program_category"],
 col_uch_program_srok |-> [ext|->0, policy |-> min, name |-> "col_uch_program_srok"],
 col_uch_program_form |-> [ext|->0, policy |-> min, name |-> "col_uch_program_form"],
 col_uch_program_target |-> [ext|->0, policy |-> min, name |-> "col_uch_program_target"],
 col_uch_program_rezult |-> [ext|->0, policy |-> min, name |-> "col_uch_program_rezult"],
 col_uch_program_mtu |-> [ext|->0, policy |-> min, name |-> "col_uch_program_mtu"],
 col_uch_program_osob |-> [ext|->0, policy |-> min, name |-> "col_uch_program_osob"],
 col_uch_program_rekom |-> [ext|->0, policy |-> min, name |-> "col_uch_program_rekom"],
 col_uch_program_att |-> [ext|->0, policy |-> min, name |-> "col_uch_program_att"],
 col_uch_program_authorlist |-> [ext|->0, policy |-> min, name |-> "col_uch_program_authorlist"],
 col_uch_program_control_qw |-> [ext|->0, policy |-> min, name |-> "col_uch_program_control_qw"],
 col_uch_program_unuse |-> [ext|->0, policy |-> min, name |-> "col_uch_program_unuse"],
 col_uch_program_napr_id |-> [ext|->0, policy |-> min, name |-> "col_uch_program_napr_id"],
 col_uch_program_department_id |-> [ext|->0, policy |-> min, name |-> "col_uch_program_department_id"],
 col_uch_program_id |-> [ext|->0, policy |-> min, name |-> "col_uch_program_id"],
 col_uch_program_head_id |-> [ext|->0, policy |-> min, name |-> "col_uch_program_head_id"],

 col_uch_programm_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_id"],
 col_uch_programm_ierarh_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_ierarh_id"],
 col_uch_programm_level |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_level"],
 col_uch_programm_count_child |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_child"],
 col_uch_programm_unuse |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_unuse"],
 col_uch_programm_programm_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_programm_id"],
 col_uch_programm_head_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_head_id"],
 col_uch_programm_razdel |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_razdel"],
 col_uch_programm_nonumeric |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_nonumeric"],
 col_uch_programm_number |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_number"],
 col_uch_programm_fullnumber |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_fullnumber"],
 col_uch_programm_name |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_name"],
 col_uch_programm_short_name |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_short_name"],
 col_uch_programm_tablo_name |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_tablo_name"],
 col_uch_programm_code |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_code"],
 col_uch_programm_data |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_data"],
 col_uch_programm_napravlenie |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_napravlenie"],
 col_uch_programm_department |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_department"],
 col_uch_programm_organization |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_organization"],
 col_uch_programm_type |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_type"],
 col_uch_programm_count_chasov |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov"],
 col_uch_programm_count_chasov_audit |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_audit"],
 col_uch_programm_count_chasov_lection |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_lection"],
 col_uch_programm_count_chasov_practik |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_practik"],
 col_uch_programm_count_chasov_seminar |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_seminar"],
 col_uch_programm_count_chasov_outer |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_outer"],
 col_uch_programm_count_chasov_outer_name |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_outer_name"],
 col_uch_programm_count_chasov_samost_prep |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_samost_prep"],
 col_uch_programm_count_chasov_samost |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_samost"],
 col_uch_programm_count_chasov_attestat |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_count_chasov_attestat"],
 col_uch_programm_category |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_category"],
 col_uch_programm_srok |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_srok"],
 col_uch_programm_form |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_form"],
 col_uch_programm_target |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_target"],
 col_uch_programm_target_seminar |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_target_seminar"],
 col_uch_programm_target_practik |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_target_practik"],
 col_uch_programm_target_samost |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_target_samost"],
 col_uch_programm_rezult |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_rezult"],
 col_uch_programm_mtu |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_mtu"],
 col_uch_programm_osob |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_osob"],
 col_uch_programm_rekom |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_rekom"],
 col_uch_programm_attestationv |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_attestationv"],
 col_uch_programm_authorlist |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_authorlist"],
 col_uch_programm_control_qw |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_control_qw"],
 col_uch_programm_control_test |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_control_test"],
 col_uch_programm_programm_link |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_programm_link"],
 col_uch_programm_index |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_index"],
 col_uch_programm_child_count |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_child_count"],
 col_uch_programm_child_razdel |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_child_razdel"],
 col_uch_programm_sname |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_sname"],
 col_uch_programm_tname |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_tname"],
 col_uch_programm_date |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_date"],
 col_uch_programm_chasov |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov"],
 col_uch_programm_chasov_aud |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_aud"],
 col_uch_programm_chasov_l |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_l"],
 col_uch_programm_chasov_p |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_p"],
 col_uch_programm_chasov_s |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_s"],
 col_uch_programm_chasov_o |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_o"],
 col_uch_programm_chasov_o_name |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_o_name"],
 col_uch_programm_chasov_sam_pr |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_sam_pr"],
 col_uch_programm_chasov_sam |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_sam"],
 col_uch_programm_chasov_att |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_chasov_att"],
 col_uch_programm_att |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_att"],
 col_uch_programm_napr_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_napr_id"],
 col_uch_programm_department_id |-> [ext|->0, policy |-> min, name |-> "col_uch_programm_department_id"],

 col_upr_department_id |-> [ext|->0, policy |-> min, name |-> "col_upr_department_id"],
 col_upr_department_head_id |-> [ext|->0, policy |-> min, name |-> "col_upr_department_head_id"],
 col_upr_department_ierarh_id |-> [ext|->0, policy |-> min, name |-> "col_upr_department_ierarh_id"],
 col_upr_department_level |-> [ext|->0, policy |-> min, name |-> "col_upr_department_level"],
 col_upr_department_count_child |-> [ext|->0, policy |-> min, name |-> "col_upr_department_count_child"],
 col_upr_department_title |-> [ext|->0, policy |-> min, name |-> "col_upr_department_title"],
 col_upr_department_short_title |-> [ext|->0, policy |-> min, name |-> "col_upr_department_short_title"],
 col_upr_department_short_title_r |-> [ext|->0, policy |-> min, name |-> "col_upr_department_short_title_r"],
 col_upr_department_rashod |-> [ext|->0, policy |-> min, name |-> "col_upr_department_rashod"],
 col_upr_department_pogar_nomer |-> [ext|->0, policy |-> min, name |-> "col_upr_department_pogar_nomer"],
 col_upr_department_ucheb |-> [ext|->0, policy |-> min, name |-> "col_upr_department_ucheb"]
 ]

Next(K(_,_)) == 
        \/ \E  s \in S :
            /\ Sessions[s]["StateRegs"] # <<>>
            /\ K(s,Sessions[s]["StateRegs"])
        \/ \A  s \in S : 
            /\ Sessions[s]["StateRegs"] = <<>>
            /\ UNCHANGED vars
SpecFS == Init /\ [] [Next(dispatch)]_vars
=============================================================================