CREATE OR REPLACE PROCEDURE P_ADD_PAPER (P_ID NUMBER, TIT VARCHAR2, ABSR VARCHAR2, T CLOB, AUTH VARCHAR2)
IS
BEGIN
INSERT INTO PAPERS (PAPER_ID, TITLE, ABSTRACT, TEXT, AUTHORS)
VALUES (P_ID, TIT, ABSR, T, AUTH);
EXCEPTION
  WHEN OTHERS
     THEN NULL;
END P_ADD_PAPER;
