CREATE OR REPLACE PROCEDURE P_ADD_PAPER (P_ID NUMBER, TIT VARCHAR2, ABSTR VARCHAR2, AUTH VARCHAR2, T CLOB)
IS
BEGIN
INSERT INTO SUBMISSIONS (PAPER_ID, TITLE, ABSTRACTION, AUTHORS, TEXT)
VALUES (P_ID, TIT, ABSR, AUTH, T);
EXCEPTION
  WHEN OTHERS
     THEN NULL;
END P_SUBMIT_PAPER;
