CREATE OR REPLACE PROCEDURE P_ALLOCATE (ID NUMBER, S_ID NUMBER, SEC_ID NUMBER, ALLOC_DATE DATE)
IS
  PAPER_NOT_ACCEPTED EXCEPTION;
  V_P_ID NUMBER;
  V_IS_ACC BOOLEAN;
BEGIN
  V_IS_ACC := F_IS_ACCEPTED (S_ID);
  IF V_IS_ACC
     THEN
SELECT PAPER_ID INTO V_P_ID
FROM SUBMISSIONS
WHERE SUBMISSION_ID = S_ID;
INSERT INTO ALLOCATIONS (ALLOCATION_ID, SUBMISSION_ID, SECTION_ID, ALLOCATION_DATE)
VALUES (ID, S_ID, SEC_ID, ALLOC_DATE);
ELSE RAISE PAPER_NOT_ACCEPTED;
END IF;
EXCEPTION
     WHEN PAPER_NOT_ACCEPTED THEN
        INSERT INTO LOGS
        VALUES (1, 'AN ATTEMPT WAS MADE TO ALLOCATE UNACCEPTED SUBMISSION ' || S_ID || ', ' || SYSDATE || '.');
WHEN OTHERS THEN
        NULL;
END P_ALLOCATE;