CREATE OR REPLACE PROCEDURE P_SUBMIT_PAPER
(S_ID NUMBER, P_ID NUMBER, C_ID NUMBER, SUB_DATE DATE, STAT NUMBER)
IS
BEGIN
P_SUBMIT_PAPER(1,1,1);
INSERT INTO SUBMISSIONS (SUBMISSION_ID, PAPER_ID, CONFERENCE_ID, SUBMISSION_DATE, STATUS)
VALUES (S_ID, P_ID, C_ID, SUB_DATE, STAT);
EXCEPTION
  WHEN OTHERS
     THEN NULL;
END P_SUBMIT_PAPER;
