------------------------------- MODULE Parameters -------------------------------
EXTENDS Naturals, Sequences
CONSTANT U, UU, NONE, ALL, E0, E1, Undef, GPol, Session_number
VARIABLES Sessions, XLocks, VPol, Trace, SLocks, Ignore, StateE, New2Old
vars == <<Sessions, SLocks, StateE, New2Old, XLocks, VPol, Trace, Ignore>>
INSTANCE Paralocks WITH U <- U, UU <- UU, NONE <- NONE, E0 <- E0, E1 <- E1, Undef <- Undef, GPol <- GPol
min == {<<CHOOSE x \in UU: TRUE, <<[e1 \in E0 |-> {NONE}],  [e2 \in E1 |-> {NONE}]>> >>}
any_caller(x) == {<<x, <<[e1 \in E0 |-> {NONE}], [e2 \in E1 |-> {NONE}]>> >>}
max == {}
u1 == CHOOSE i \in UU: TRUE
u2 == CHOOSE j \in UU: j#u1
S ==  CHOOSE s \in SUBSET(U) : Cardinality(s) = Session_number

col_meth_author_id == [loc|->"persistence", policy |-> min]
col_meth_author_f == [loc|->"persistence", policy |-> min]
col_meth_author_i == [loc|->"persistence", policy |-> min]
col_meth_author_o == [loc|->"persistence", policy |-> min]
col_meth_author_full == [loc|->"persistence", policy |-> min]
col_meth_author_fio == [loc|->"persistence", policy |-> min]

col_meth_book_access_id == [loc|->"persistence", policy |-> min]
col_meth_book_access_book_id == [loc|->"persistence", policy |-> min]
col_meth_book_access_account_id == [loc|->"persistence", policy |-> min]

col_meth_book_catalog_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_timestamp == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_code == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_serial_select == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_1 == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_svedeniya == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_ISBN == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_ISSN == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_period_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_regulative == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_vypusk == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_number == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_part == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_number_part == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_publishing_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_city1_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_date_publication == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_volume == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_illustration == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_anotation == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_1_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_dr == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_2_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_3_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_UDK == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_znak == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_key_word == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_language_text_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_language_resume_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_country_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_type_media_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_electronic_media == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_type_publishing_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_vid_edition_key == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_characters_edition_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_2 == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_city2_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_city3_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_attachments == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_title_serial == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_number_serial == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_republishing == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_autor_t_id == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_original_ISBN == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_original_ISSN == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_daktors == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_organization == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_stelag == [loc|->"persistence", policy |-> min]
col_meth_book_catalog_polka == [loc|->"persistence", policy |-> min]

col_meth_book_content_id == [loc|->"persistence", policy |-> min]
col_meth_book_content_book_id == [loc|->"persistence", policy |-> min]
col_meth_book_content_head_id == [loc|->"persistence", policy |-> min]
col_meth_book_content_ierarh_id == [loc|->"persistence", policy |-> min]
col_meth_book_content_level == [loc|->"persistence", policy |-> min]
col_meth_book_content_nonumeric == [loc|->"persistence", policy |-> min]
col_meth_book_content_number == [loc|->"persistence", policy |-> min]
col_meth_book_content_fullnumber == [loc|->"persistence", policy |-> min]
col_meth_book_content_count_child == [loc|->"persistence", policy |-> min]
col_meth_book_content_name == [loc|->"persistence", policy |-> min]
col_meth_book_content_desc == [loc|->"persistence", policy |-> min]
col_meth_book_content_naprav_id == [loc|->"persistence", policy |-> min]
col_meth_book_content_public == [loc|->"persistence", policy |-> min]
col_meth_book_content_autor == [loc|->"persistence", policy |-> min]

col_meth_publishing_id == [loc|->"persistence", policy |-> min]
col_meth_publishing_type == [loc|->"persistence", policy |-> min]
col_meth_publishing_title == [loc|->"persistence", policy |-> min]
col_meth_publishing_adress == [loc|->"persistence", policy |-> min]
col_meth_publishing_URL == [loc|->"persistence", policy |-> min]
col_meth_publishing_email == [loc|->"persistence", policy |-> min]

col_meth_test_content_id == [loc|->"persistence", policy |-> min]
col_meth_test_content_test_id == [loc|->"persistence", policy |-> min]
col_meth_test_content_head_id == [loc|->"persistence", policy |-> min]
col_meth_test_content_ierarh_id == [loc|->"persistence", policy |-> min]
col_meth_test_content_level == [loc|->"persistence", policy |-> min]
col_meth_test_content_count_child == [loc|->"persistence", policy |-> min]
col_meth_test_content_name == [loc|->"persistence", policy |-> min]
col_meth_test_content_desc == [loc|->"persistence", policy |-> min]
col_meth_test_content_desc_text == [loc|->"persistence", policy |-> min]
col_meth_test_content_naprav_id == [loc|->"persistence", policy |-> min]
col_meth_test_content_time == [loc|->"persistence", policy |-> min]
col_meth_test_content_rundom == [loc|->"persistence", policy |-> min]
col_meth_test_content_public == [loc|->"persistence", policy |-> min]
col_meth_test_content_anonim == [loc|->"persistence", policy |-> min]
col_meth_test_content_autor == [loc|->"persistence", policy |-> min]
col_meth_test_content_ucheb == [loc|->"persistence", policy |-> min]
col_meth_test_content_terminal == [loc|->"persistence", policy |-> min]
col_meth_test_content_end_terminal == [loc|->"persistence", policy |-> min]
col_meth_test_content_razdel_number == [loc|->"persistence", policy |-> min]
col_meth_test_content_razdel_count_answer == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_multiselect == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_methodik == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_obligatory == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_time == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_count_answer == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_all_number == [loc|->"persistence", policy |-> min]
col_meth_test_content_qweshion_number == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_correct == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_negative == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_bal == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_input == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_input_int == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_input_text == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_min == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_max == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_ignor_qw == [loc|->"persistence", policy |-> min]
col_meth_test_content_answer_number == [loc|->"persistence", policy |-> min]

col_uch_liter_id == [loc|->"persistence", policy |-> min]
col_uch_liter_programm_id == [loc|->"persistence", policy |-> min]
col_uch_liter_book_id == [loc|->"persistence", policy |-> min]
col_uch_liter_name == [loc|->"persistence", policy |-> min]
col_uch_liter_osnovnaya == [loc|->"persistence", policy |-> min]
col_uch_create_user == [loc|->"persistence", policy |-> min]
col_uch_create_date == [loc|->"persistence", policy |-> min]
col_uch_edit_user == [loc|->"persistence", policy |-> min]
col_uch_edit_date == [loc|->"persistence", policy |-> min]

col_uch_napravlenie_id == [loc|->"persistence", policy |-> min]
col_uch_napravlenie_head_id == [loc|->"persistence", policy |-> min]
col_uch_napravlenie_name == [loc|->"persistence", policy |-> min]
col_uch_napravlenie_short_name == [loc|->"persistence", policy |-> min]
col_uch_napravlenie_code == [loc|->"persistence", policy |-> min]
col_uch_napravlenie_order == [loc|->"persistence", policy |-> min]

col_uch_programm_id == [loc|->"persistence", policy |-> min]
col_uch_programm_ierarh_id == [loc|->"persistence", policy |-> min]
col_uch_programm_level == [loc|->"persistence", policy |-> min]
col_uch_programm_count_child == [loc|->"persistence", policy |-> min]
col_uch_programm_unuse == [loc|->"persistence", policy |-> min]
col_uch_programm_programm_id == [loc|->"persistence", policy |-> min]
col_uch_programm_head_id == [loc|->"persistence", policy |-> min]
col_uch_programm_razdel == [loc|->"persistence", policy |-> min]
col_uch_programm_nonumeric == [loc|->"persistence", policy |-> min]
col_uch_programm_number == [loc|->"persistence", policy |-> min]
col_uch_programm_fullnumber == [loc|->"persistence", policy |-> min]
col_uch_programm_name == [loc|->"persistence", policy |-> min]
col_uch_programm_short_name == [loc|->"persistence", policy |-> min]
col_uch_programm_tablo_name == [loc|->"persistence", policy |-> min]
col_uch_programm_code == [loc|->"persistence", policy |-> min]
col_uch_programm_data == [loc|->"persistence", policy |-> min]
col_uch_programm_napravlenie == [loc|->"persistence", policy |-> min]
col_uch_programm_department == [loc|->"persistence", policy |-> min]
col_uch_programm_organization == [loc|->"persistence", policy |-> min]
col_uch_programm_type == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_audit == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_lection == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_practik == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_seminar == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_outer == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_outer_name == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_samost_prep == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_samost == [loc|->"persistence", policy |-> min]
col_uch_programm_count_chasov_attestat == [loc|->"persistence", policy |-> min]
col_uch_programm_category == [loc|->"persistence", policy |-> min]
col_uch_programm_srok == [loc|->"persistence", policy |-> min]
col_uch_programm_form == [loc|->"persistence", policy |-> min]
col_uch_programm_target == [loc|->"persistence", policy |-> min]
col_uch_programm_target_seminar == [loc|->"persistence", policy |-> min]
col_uch_programm_target_practik == [loc|->"persistence", policy |-> min]
col_uch_programm_target_samost == [loc|->"persistence", policy |-> min]
col_uch_programm_rezult == [loc|->"persistence", policy |-> min]
col_uch_programm_mtu == [loc|->"persistence", policy |-> min]
col_uch_programm_osob == [loc|->"persistence", policy |-> min]
col_uch_programm_rekom == [loc|->"persistence", policy |-> min]
col_uch_programm_attestation == [loc|->"persistence", policy |-> min]
col_uch_programm_authorlist == [loc|->"persistence", policy |-> min]
col_uch_programm_control_qw == [loc|->"persistence", policy |-> min]
col_uch_programm_control_test == [loc|->"persistence", policy |-> min]
col_uch_programm_programm_link == [loc|->"persistence", policy |-> min]
col_uch_programm_index == [loc|->"persistence", policy |-> min]

col_uch_programm_mtu_id == [loc|->"persistence", policy |-> min]
col_uch_programm_mtu_programm_id == [loc|->"persistence", policy |-> min]
col_uch_programm_mtu_name == [loc|->"persistence", policy |-> min]

col_uch_programm_unmtu_id == [loc|->"persistence", policy |-> min]
col_uch_programm_unmtu_programm_id == [loc|->"persistence", policy |-> min]
col_uch_programm_unmtu_mtu_id == [loc|->"persistence", policy |-> min]
col_uch_programm_unmtu_type == [loc|->"persistence", policy |-> min]

col_upr_account_id == [loc|->"persistence", policy |-> min]
col_upr_account_f == [loc|->"persistence", policy |-> min]
col_upr_account_f_r == [loc|->"persistence", policy |-> min]
col_upr_account_f_t == [loc|->"persistence", policy |-> min]
col_upr_account_f_d == [loc|->"persistence", policy |-> min]
col_upr_account_i == [loc|->"persistence", policy |-> min]
col_upr_account_i_r == [loc|->"persistence", policy |-> min]
col_upr_account_i_t == [loc|->"persistence", policy |-> min]
col_upr_account_i_d == [loc|->"persistence", policy |-> min]
col_upr_account_o == [loc|->"persistence", policy |-> min]
col_upr_account_o_r == [loc|->"persistence", policy |-> min]
col_upr_account_o_t == [loc|->"persistence", policy |-> min]
col_upr_account_o_d == [loc|->"persistence", policy |-> min]
col_upr_account_full == [loc|->"persistence", policy |-> min]
col_upr_account_fio == [loc|->"persistence", policy |-> min]
col_upr_account_podp == [loc|->"persistence", policy |-> min]
col_upr_account_podp2 == [loc|->"persistence", policy |-> min]
col_upr_account_pol == [loc|->"persistence", policy |-> min]
col_upr_account_dept == [loc|->"persistence", policy |-> min]
col_upr_account_dept_shtat == [loc|->"persistence", policy |-> min]
col_upr_account_range == [loc|->"persistence", policy |-> min]
col_upr_account_bd == [loc|->"persistence", policy |-> min]
col_upr_account_bd_string == [loc|->"persistence", policy |-> min]
col_upr_account_zvanie_id == [loc|->"persistence", policy |-> min]
col_upr_account_office_id == [loc|->"persistence", policy |-> min]
col_upr_account_worktel == [loc|->"persistence", policy |-> min]
col_upr_account_worktel_dop == [loc|->"persistence", policy |-> min]
col_upr_account_worktel_os == [loc|->"persistence", policy |-> min]
col_upr_account_hometel == [loc|->"persistence", policy |-> min]
col_upr_account_homeadress == [loc|->"persistence", policy |-> min]
col_upr_account_homeputh == [loc|->"persistence", policy |-> min]
col_upr_account_hometime == [loc|->"persistence", policy |-> min]
col_upr_account_mobile == [loc|->"persistence", policy |-> min]
col_upr_account_domain_name == [loc|->"persistence", policy |-> min]
col_upr_account_samid == [loc|->"persistence", policy |-> min]
col_upr_account_online == [loc|->"persistence", policy |-> min]
col_upr_account_foto_file_type == [loc|->"persistence", policy |-> min]
col_upr_account_foto_file_length == [loc|->"persistence", policy |-> min]
col_upr_account_foto_file_value == [loc|->"persistence", policy |-> min]

col_upr_department_id == [loc|->"persistence", policy |-> min]
col_upr_department_head_id == [loc|->"persistence", policy |-> min]
col_upr_department_ierarh_id == [loc|->"persistence", policy |-> min]
col_upr_department_level == [loc|->"persistence", policy |-> min]
col_upr_department_count_child == [loc|->"persistence", policy |-> min]
col_upr_department_title == [loc|->"persistence", policy |-> min]
col_upr_department_short_title == [loc|->"persistence", policy |-> min]
col_upr_department_short_title_r == [loc|->"persistence", policy |-> min]
col_upr_department_rashod == [loc|->"persistence", policy |-> min]
col_upr_department_pogar_nomer == [loc|->"persistence", policy |-> min]
col_upr_department_ucheb == [loc|->"persistence", policy |-> min]

col_upr_range_head_id == [loc|->"persistence", policy |-> min]
col_upr_range_ierarh_id == [loc|->"persistence", policy |-> min]
col_upr_range_level == [loc|->"persistence", policy |-> min]
col_upr_range_count_child == [loc|->"persistence", policy |-> min]
col_upr_range_dept_id == [loc|->"persistence", policy |-> min]
col_upr_range_title == [loc|->"persistence", policy |-> min]
col_upr_range_short_title == [loc|->"persistence", policy |-> min]
col_upr_range_head == [loc|->"persistence", policy |-> min]
col_upr_range_sys == [loc|->"persistence", policy |-> min]
col_upr_range_unuse == [loc|->"persistence", policy |-> min]

col_upr_zv_head_id == [loc|->"persistence", policy |-> min]
col_upr_zv_ierarh_id == [loc|->"persistence", policy |-> min]
col_upr_zv_level == [loc|->"persistence", policy |-> min]
col_upr_zv_count_child == [loc|->"persistence", policy |-> min]
col_upr_zv_group == [loc|->"persistence", policy |-> min]
col_upr_zv_unuse == [loc|->"persistence", policy |-> min]
col_upr_zv_timestamp == [loc|->"persistence", policy |-> min]
col_upr_zv_code == [loc|->"persistence", policy |-> min]
col_upr_zv_name == [loc|->"persistence", policy |-> min]
col_upr_zv_name_rodit == [loc|->"persistence", policy |-> min]
col_upr_zv_name_tvorit == [loc|->"persistence", policy |-> min]
col_upr_zv_name_dat == [loc|->"persistence", policy |-> min]
col_upr_zv_short_name == [loc|->"persistence", policy |-> min]
col_upr_zv_rang == [loc|->"persistence", policy |-> min]
col_upr_zv_state == [loc|->"persistence", policy |-> min]
col_upr_zv_order == [loc|->"persistence", policy |-> min]

f_UCHEBA_programm_list_p_data_view(x) == [loc|->"mem", offs |-> 0, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_view"]
f_UCHEBA_programm_list_p_data_unuse(x) == [loc|->"mem", offs |-> 1, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_unuse"]
f_UCHEBA_programm_list_p_data_name(x) == [loc|->"mem", offs |-> 2, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_name"]
f_UCHEBA_programm_list_p_data_code(x) == [loc|->"mem", offs |-> 3, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_code"]
f_UCHEBA_programm_list_p_date_n(x) == [loc|->"mem", offs |-> 4, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_date_n"]
f_UCHEBA_programm_list_p_date_o(x) == [loc|->"mem", offs |-> 5, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_date_o"]
f_UCHEBA_programm_list_p_data_naprav(x) == [loc|->"mem", offs |-> 6, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_naprav"]
f_UCHEBA_programm_list_p_data_kafedra(x) == [loc|->"mem", offs |-> 7, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_kafedra"]
f_UCHEBA_programm_list_p_data_chacov_n(x) == [loc|->"mem", offs |-> 8, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_chacov_n"]
f_UCHEBA_programm_list_p_data_chacov_o(x) == [loc|->"mem", offs |-> 9, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_p_data_chacov_o"]
f_UCHEBA_programm_list_v_r_rec_c1(x) == [loc|->"mem", offs |-> 10, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c1"]
f_UCHEBA_programm_list_v_r_rec_c2(x) == [loc|->"mem", offs |-> 11, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c2"]
f_UCHEBA_programm_list_v_r_rec_c3(x) == [loc|->"mem", offs |-> 12, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c3"]
f_UCHEBA_programm_list_v_r_rec_c4(x) == [loc|->"mem", offs |-> 13, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c4"]
f_UCHEBA_programm_list_v_r_rec_c5(x) == [loc|->"mem", offs |-> 14, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c5"]
f_UCHEBA_programm_list_v_r_rec_c6(x) == [loc|->"mem", offs |-> 15, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c6"]
f_UCHEBA_programm_list_v_r_rec_c7(x) == [loc|->"mem", offs |-> 16, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c7"]
f_UCHEBA_programm_list_v_r_rec_c8(x) == [loc|->"mem", offs |-> 17, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c8"]
f_UCHEBA_programm_list_v_r_rec_c9(x) == [loc|->"mem", offs |-> 18, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c9"]
f_UCHEBA_programm_list_v_r_rec_c10(x) == [loc|->"mem", offs |-> 19, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c10"]
f_UCHEBA_programm_list_v_r_rec_c11(x) == [loc|->"mem", offs |-> 20, policy |-> min, name |-> "f_UCHEBA_programm_list_v_r_rec_c11"]
f_UCHEBA_programm_list_r_rec_c1(x) == [loc|->"mem", offs |-> 21, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c1"]
f_UCHEBA_programm_list_r_rec_c2(x) == [loc|->"mem", offs |-> 22, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c2"]
f_UCHEBA_programm_list_r_rec_c3(x) == [loc|->"mem", offs |-> 23, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c3"]
f_UCHEBA_programm_list_r_rec_c4(x) == [loc|->"mem", offs |-> 24, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c4"]
f_UCHEBA_programm_list_r_rec_c5(x) == [loc|->"mem", offs |-> 25, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c5"]
f_UCHEBA_programm_list_r_rec_c6(x) == [loc|->"mem", offs |-> 26, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c6"]
f_UCHEBA_programm_list_r_rec_c7(x) == [loc|->"mem", offs |-> 27, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c7"]
f_UCHEBA_programm_list_r_rec_c8(x) == [loc|->"mem", offs |-> 28, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c8"]
f_UCHEBA_programm_list_r_rec_c9(x) == [loc|->"mem", offs |-> 29, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c9"]
f_UCHEBA_programm_list_r_rec_c10(x) == [loc|->"mem", offs |-> 30, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c10"]
f_UCHEBA_programm_list_r_rec_c11(x) == [loc|->"mem", offs |-> 31, policy |-> any_caller(x), name |-> "f_UCHEBA_programm_list_r_rec_c11"]

=============================================================================