CREATE OR REPLACE FUNCTION F_IS_ACCEPTED (S_ID NUMBER) RETURN BOOLEAN
IS
   V_STATUS NUMBER;
BEGIN
SELECT STATUS INTO V_STATUS
FROM SUBMISSIONS
WHERE SUBMISSION_ID = S_ID;
IF V_STATUS = 1
     THEN RETURN TRUE;
ELSE RETURN FALSE;
END IF;
END F_IS_ACCEPTED;